language: node_js

node_js:
  - "14"

# build matrix with envs for different MSB versions
env:
  - TESTENV_BROKER_URL=https://ws.15xr.msb.oss.cell.vfk.fraunhofer.de/ TESTENV_SO_URL=https://so.15xr.msb.oss.cell.vfk.fraunhofer.de/ TESTENV_FLOW_URL=https://flow.15xr.msb.oss.cell.vfk.fraunhofer.de/
  - DEPLOY_MSB_CLIENT_LIB=yes TESTENV_BROKER_URL=https://ws.16xr.msb.oss.cell.vfk.fraunhofer.de/ TESTENV_SO_URL=https://so.16xr.msb.oss.cell.vfk.fraunhofer.de/ TESTENV_FLOW_URL=https://flow.16xr.msb.oss.cell.vfk.fraunhofer.de/

cache: npm

# npm test is executed here by default, change it here:
script:
  - npm run test:all

after_success:
  - npm run coverage:coveralls

deploy:
  provider: npm # deploys to npmjs repo
  email: $NPMJS_EMAIL
  api_key: $NPMJS_PASSWORD
  on:
    tags: true # only deploys if a git TAG exists for the commit
    condition: $DEPLOY_MSB_CLIENT_LIB = yes # only deploys if condition true
    # branch: master # only deploys if branch is master